Imports System.Drawing.Printing

Public Module ReportPrinter

    Private _records As List(Of RecordModel)
    Private _stationName As String
    Private _printedBy As String

    Public Sub Preview(records As List(Of RecordModel), stationName As String, printedBy As String)
        _records    = records
        _stationName = stationName
        _printedBy  = printedBy

        Dim doc As New PrintDocument()
        doc.DocumentName = "RMIS Fire Incident Report"
        doc.DefaultPageSettings.Margins = New Margins(80, 80, 80, 80)
        AddHandler doc.PrintPage, AddressOf DrawPage

        Using dlg As New PrintPreviewDialog()
            dlg.Document     = doc
            dlg.WindowState  = FormWindowState.Maximized
            dlg.Text         = "Print Preview — Fire Incident Report"
            dlg.ShowDialog()
        End Using
    End Sub

    Private Sub DrawPage(sender As Object, e As PrintPageEventArgs)
        Dim g  = e.Graphics
        Dim b  = e.MarginBounds
        Dim y  = b.Top

        ' ── Fonts ────────────────────────────────────────────────
        Dim fStation  = New Font("Segoe UI", 10, FontStyle.Bold)
        Dim fTitle    = New Font("Segoe UI", 18, FontStyle.Bold)
        Dim fSub      = New Font("Segoe UI", 9)
        Dim fSection  = New Font("Segoe UI", 10, FontStyle.Bold)
        Dim fColHdr   = New Font("Segoe UI", 9,  FontStyle.Bold)
        Dim fCell     = New Font("Segoe UI", 9)
        Dim fTotals   = New Font("Segoe UI", 9,  FontStyle.Bold)
        Dim fFooter   = New Font("Segoe UI", 7.5F)
        Dim fCardNum  = New Font("Segoe UI", 20, FontStyle.Bold)
        Dim fCardLbl  = New Font("Segoe UI", 8)

        ' ── Brushes & Pens ───────────────────────────────────────
        Dim red       = Color.FromArgb(180, 20, 20)
        Dim brRed     = New SolidBrush(red)
        Dim brBlack   = New SolidBrush(Color.FromArgb(30, 30, 30))
        Dim brGray    = New SolidBrush(Color.Gray)
        Dim brWhite   = New SolidBrush(Color.White)
        Dim brRowAlt  = New SolidBrush(Color.FromArgb(250, 250, 250))
        Dim brOrange  = New SolidBrush(Color.FromArgb(220, 120, 0))
        Dim brGreen   = New SolidBrush(Color.FromArgb(30, 130, 30))
        Dim brDkGray  = New SolidBrush(Color.FromArgb(100, 100, 100))
        Dim penRed    = New Pen(red, 2)
        Dim penLight  = New Pen(Color.FromArgb(210, 210, 210), 0.5F)
        Dim penDark   = New Pen(Color.FromArgb(170, 170, 170), 1)

        ' ── String formats ───────────────────────────────────────
        Dim sfLeft   As New StringFormat() With {.LineAlignment = StringAlignment.Center}
        Dim sfCenter As New StringFormat() With {.Alignment = StringAlignment.Center,
                                                  .LineAlignment = StringAlignment.Center}
        Dim sfRight  As New StringFormat() With {.Alignment = StringAlignment.Far,
                                                  .LineAlignment = StringAlignment.Center}

        ' ════════════════════════════════════════════════════════
        ' HEADER
        ' ════════════════════════════════════════════════════════
        g.DrawString(_stationName.ToUpper(), fStation, brRed, b.Left, y)
        y += 22
        g.DrawString("Fire Incident Report", fTitle, brBlack, b.Left, y)
        y += 34
        g.DrawString("Bureau of Fire Protection — Tuao Fire Station", fSub, brGray, b.Left, y)
        y += 18
        g.DrawString(
            "Date Generated: " & DateTime.Now.ToString("MMMM dd, yyyy  hh:mm tt") &
            "     Generated by: " & _printedBy,
            fSub, brGray, b.Left, y)
        y += 14
        g.DrawLine(penRed, b.Left, y, b.Right, y)
        y += 18

        ' ════════════════════════════════════════════════════════
        ' SUMMARY CARDS
        ' ════════════════════════════════════════════════════════
        Dim total    = _records.Count
        Dim active   = _records.Where(Function(r) r.Status = "Active").Count()
        Dim resolved = _records.Where(Function(r) r.Status = "Resolved").Count()
        Dim closed   = _records.Where(Function(r) r.Status = "Closed").Count()
        Dim other    = total - active - resolved - closed

        g.DrawString("SUMMARY", fSection, brBlack, b.Left, y)
        y += 20

        Dim gap  = 10
        Dim boxW = (b.Width - gap * 3) \ 4
        Dim boxH = 56

        Dim cards = {
            ("Total Incidents", total.ToString(),    brBlack),
            ("Active",          active.ToString(),   brOrange),
            ("Resolved",        resolved.ToString(), brGreen),
            ("Closed",          closed.ToString(),   brDkGray)
        }

        For i = 0 To 3
            Dim cx = b.Left + i * (boxW + gap)
            Dim cardRect = New Rectangle(cx, y, boxW, boxH)
            g.FillRectangle(New SolidBrush(Color.FromArgb(248, 248, 248)), cardRect)
            g.DrawRectangle(penDark, cardRect)
            g.DrawString(cards(i).Item1, fCardLbl, brGray,
                         New Rectangle(cx + 8, y + 6, boxW - 12, 16), sfLeft)
            g.DrawString(cards(i).Item2, fCardNum, cards(i).Item3,
                         New Rectangle(cx + 6, y + 20, boxW - 12, 32), sfLeft)
        Next
        y += boxH + 20

        ' ════════════════════════════════════════════════════════
        ' BREAKDOWN TABLE
        ' ════════════════════════════════════════════════════════
        g.DrawLine(penLight, b.Left, y, b.Right, y)
        y += 12
        g.DrawString("BREAKDOWN BY INCIDENT TYPE", fSection, brBlack, b.Left, y)
        y += 20

        ' Column x positions & widths
        Dim c0w = CInt(b.Width * 0.36)
        Dim c1w = CInt(b.Width * 0.16)
        Dim c2w = CInt(b.Width * 0.16)
        Dim c3w = CInt(b.Width * 0.16)
        Dim c4w = b.Width - c0w - c1w - c2w - c3w

        Dim x0 = b.Left
        Dim x1 = x0 + c0w
        Dim x2 = x1 + c1w
        Dim x3 = x2 + c2w
        Dim x4 = x3 + c3w

        Dim rowH = 24

        ' Header row
        g.FillRectangle(brRed, New Rectangle(b.Left, y, b.Width, rowH))
        g.DrawString("Incident Type", fColHdr, brWhite, New Rectangle(x0 + 6, y, c0w, rowH), sfLeft)
        g.DrawString("Total",    fColHdr, brWhite, New Rectangle(x1, y, c1w, rowH), sfCenter)
        g.DrawString("Active",   fColHdr, brWhite, New Rectangle(x2, y, c2w, rowH), sfCenter)
        g.DrawString("Resolved", fColHdr, brWhite, New Rectangle(x3, y, c3w, rowH), sfCenter)
        g.DrawString("Other",    fColHdr, brWhite, New Rectangle(x4, y, c4w, rowH), sfCenter)
        y += rowH

        ' Data rows
        Dim types = _records.Select(Function(r) r.IncidentType).Distinct().OrderBy(Function(t) t).ToList()
        Dim alt   = False
        For Each incType In types
            Dim grp       = _records.Where(Function(r) r.IncidentType = incType).ToList()
            Dim gActive   = grp.Where(Function(r) r.Status = "Active").Count()
            Dim gResolved = grp.Where(Function(r) r.Status = "Resolved").Count()
            Dim gOther    = grp.Count - gActive - gResolved

            Dim rowBrush = If(alt, brRowAlt, New SolidBrush(Color.White))
            g.FillRectangle(rowBrush, New Rectangle(b.Left, y, b.Width, rowH))
            g.DrawLine(penLight, b.Left, y + rowH, b.Right, y + rowH)

            g.DrawString(incType,           fCell, brBlack, New Rectangle(x0 + 6, y, c0w - 6, rowH), sfLeft)
            g.DrawString(grp.Count.ToString(), fCell, brBlack, New Rectangle(x1, y, c1w, rowH), sfCenter)
            g.DrawString(gActive.ToString(),   fCell, brBlack, New Rectangle(x2, y, c2w, rowH), sfCenter)
            g.DrawString(gResolved.ToString(), fCell, brBlack, New Rectangle(x3, y, c3w, rowH), sfCenter)
            g.DrawString(gOther.ToString(),    fCell, brBlack, New Rectangle(x4, y, c4w, rowH), sfCenter)

            y += rowH
            alt = Not alt
        Next

        ' Totals row
        y += 2
        g.DrawLine(penRed, b.Left, y, b.Right, y)
        y += 2
        g.FillRectangle(New SolidBrush(Color.FromArgb(245, 245, 245)),
                        New Rectangle(b.Left, y, b.Width, rowH))
        g.DrawString("TOTAL",          fTotals, brBlack, New Rectangle(x0 + 6, y, c0w - 6, rowH), sfLeft)
        g.DrawString(total.ToString(), fTotals, brBlack, New Rectangle(x1, y, c1w, rowH), sfCenter)
        g.DrawString(active.ToString(), fTotals, brBlack, New Rectangle(x2, y, c2w, rowH), sfCenter)
        g.DrawString(resolved.ToString(), fTotals, brBlack, New Rectangle(x3, y, c3w, rowH), sfCenter)
        g.DrawString(other.ToString(), fTotals, brBlack, New Rectangle(x4, y, c4w, rowH), sfCenter)

        ' ════════════════════════════════════════════════════════
        ' FOOTER
        ' ════════════════════════════════════════════════════════
        Dim fy = b.Bottom - 20
        g.DrawLine(penLight, b.Left, fy, b.Right, fy)
        g.DrawString(
            "Bureau of Fire Protection — Tuao Fire Station  |  This report is system-generated.",
            fFooter, brGray, b.Left, fy + 4)
        g.DrawString("Page 1", fFooter, brGray,
                     New Rectangle(b.Left, fy + 4, b.Width, 16), sfRight)

        ' ── Dispose ──────────────────────────────────────────────
        For Each f In {fStation, fTitle, fSub, fSection, fColHdr, fCell, fTotals, fFooter, fCardNum, fCardLbl}
            f.Dispose()
        Next
        For Each br In {brRed, brBlack, brGray, brWhite, brRowAlt, brOrange, brGreen, brDkGray}
            br.Dispose()
        Next
        penRed.Dispose()
        penLight.Dispose()
        penDark.Dispose()

        e.HasMorePages = False
    End Sub

End Module
